// loginTypes.js

const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const SET_ADMIN = 'SET_ADMIN';
const LOGOUT = 'LOGOUT';
export {
  LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT, SET_ADMIN,
};
